spring.application.name=JournalFinderBackend
spring.datasource.url=jdbc:sqlite:../CompSciencePub.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Hibernate Dialect specific setting
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# Server port
server.port=8080
